version: '3.8'

services:
  app:
    build: .
    image: unet-iris:latest
    container_name: fastapi-model

    ports:
      - "8001:8001"

    environment:
      - PYTHONUNBUFFERED=1

    shm_size: '2gb'
    mem_limit: 6g
    mem_reservation: 2g

    restart: unless-stopped

    volumes:
      - .:/app    # syncs full project including images/

    working_dir: /app